repos:
-   repo: local
    hooks:
    - id: gitleaks
      name: Detect hardcoded secrets
      description: Detect hardcoded secrets using Gitleaks
      entry: gitleaks protect --config="gitleaks-nhsbsa.toml" --verbose --redact --staged
      language: system
      pass_filenames: false